services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Maispace\MaiMember\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  Maispace\MaiMember\Controller\MemberController:
    public: true

  Maispace\MaiMember\Controller\ApplicationController:
    public: true

  Maispace\MaiMember\Controller\Backend\MemberBackendController:
    public: true
